### ISSUE TITLE
 Limitation of friendships

### ISSUE THREAD

**Issue by bypit** [hootlex/laravel-friendships#1]
Is it possible to add a Limitation of friendships to the package. I mean e.g. that user (A) can only have 10 Friends and User (B) 20. And the Limitations saved in DB

If you can add this, I would be really happy about that

**Comment by hootlex** [comment]
Hmm that's an interesting but tricky feature. 
Say for example that a user has a limit of 10 friends, he already has 7 friends 4 pending requests and another user wants to sent him a friend request, what do you expect to happen?
