### ISSUE TITLE
basic flow to send request 

### ISSUE THREAD

**Issue by thakurabhishek795** [hootlex/laravel-friendships#101]
1)what field needs to send? what I should I write in resource/view  files
2)where does it go? to the controller? how should I implement Friendable trait in that controller?
3) is this necessary to add Friendable trait to User model?
@hootlex @nikolaynesov @nahid @bryant1410 @davidavz @irazasyed

**Comment by davidavz** [comment]
Hi.

You have to add the Friendable trait into the model you want to act with (in most of the case it's the User model).

Then you can call the differents methods with your User instance. It's up to you to call them in a Controller, a View ...
It depends on what you want to do.

**Comment by thakurabhishek795** [comment]
thankyou
