### ISSUE TITLE
[bug] User sending the friend request can accept it to be friends

### ISSUE THREAD

**Issue by computerfr33k** [hootlex/laravel-friendships#11]
There is a bug with your sql statements that allows the person sending the friend request to accept it because it uses the findFriendship method.

```php
public function acceptFriendRequest(Model $recipient)
    {
        return $this->findFriendship($recipient)->update([
            'status' => Status::ACCEPTED,
        ]);
    }
```
uses
```php
public function scopeBetweenModels($query, $sender, $recipient)
    {
        return $query->where(function ($q) use ($sender, $recipient) {
                    $q->whereSender($sender)->whereRecipient($recipient);
                })->orWhere(function ($q) use ($sender, $recipient) {
                    $q->whereSender($recipient)->whereRecipient($sender);
                });
    }
```

The problem is that this method returns the row if the recipient is either the sender OR the recipient. (if that makes sense). And so, this allows the sender to then accept it since it is matching either them as the sender OR the recipient and then it does an update on that row.

**Comment by hootlex** [comment]
This was not an sql bug.
I assumed that you wont run `acceptFriendship` this way.

Anyway, I fixed it in [v1.0.9](https://github.com/hootlex/laravel-friendships/releases/tag/v1.0.9)
thanks!
