### ISSUE TITLE
Friendship always accepted

### ISSUE THREAD

**Issue by VitoFamiglietti** [hootlex/laravel-friendships#12]
When I send a friendship request to a model, when I check if a model is friend with another (using $user->isFriendWith($recipient), it will return me always true, even if the request is still pending.

**Comment by Advil-Robin** [comment]
Got the same issue here.

**Comment by hootlex** [comment]
That's weird. Which version do you use guys?

The tests show that it is working correctly on v1.0.9

![](http://i.imgur.com/BKjGiQd.png)

**Comment by hootlex** [comment]
@Advil-Robin @VitoFamiglietti is this still an issue?

**Comment by VitoFamiglietti** [comment]
Yes, when I dd it still returns me true even if the friendship is still
pending
Il giorno gio 3 mar 2016 alle 04:32 Alex Kyriakidis <
notifications@github.com> ha scritto:

**Comment by hootlex** [comment]
Which version of the package do you use?
Στις 3 Μαρ 2016 19:09, ο χρήστης "Vito" <notifications@github.com> έγραψε:

**Comment by VitoFamiglietti** [comment]
the dev version. i guess the 1.9

Il giorno gio 3 mar 2016 alle ore 19:14 Alex Kyriakidis <
notifications@github.com> ha scritto:

**Comment by hootlex** [comment]
Have you tried to update the package?
Στις 3 Μαρ 2016 20:16, ο χρήστης "Vito" <notifications@github.com> έγραψε:

**Comment by VitoFamiglietti** [comment]
Yes, and it seems works now. Thanks :)

Il giorno gio 3 mar 2016 alle ore 19:19 Alex Kyriakidis <
notifications@github.com> ha scritto:

**Comment by hootlex** [comment]
Good :)
