### ISSUE TITLE
Will this work

### ISSUE THREAD

**Issue by CactusJasper** [hootlex/laravel-friendships#133]
Will this work in Laravel 6.x
I know this isn't an issue, however, I would love to know

**Comment by ractoon** [comment]
I'm currently using this in a Laravel 6 project. Things seem to be working as expected.

**Comment by kingga** [comment]
@ractoon I'm using this in Laravel 6 as well and their seems to be a problem with events.

`Call to undefined method Illuminate\Events\Dispatcher::fire()`

Small trace:

```
0:
message: "Call to undefined method Illuminate\Events\Dispatcher::fire()"
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "/home/vagrant/isapi/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php"
line: 261

1:
file: "/home/vagrant/isapi/vendor/hootlex/laravel-friendships/src/Traits/Friendable.php"
line: 35
function: "__callStatic"
class: "Illuminate\Support\Facades\Facade"
type: "::"

2:
file: "/home/vagrant/isapi/app/Http/Controllers/FriendshipController.php"
line: 35
function: "befriend"
class: "App\User"
type: "->"
```

If you want to use this as I did I would recommend forking it and just changing everything which uses `Event::fire` to `Event::dispatch` in `/src/Traits/Friendable.php`. Their is a pull request for this already but it seems to have some issues #132.

**Comment by CactusJasper** [comment]
ok thank you it's working fine now
