### ISSUE TITLE
denyFriendRequest

### ISSUE THREAD

**Issue by Tiaan1** [hootlex/laravel-friendships#18]
Hi There, 

So if one of my users sent a friend request to another and the user denies the friend request it turns the status to 2 in database, however shouldn't the user have the option to resend the friend request again? this is not working, as soon as the status is set to 2 the user cannot send any more friend request to specific user.

**Comment by Tiaan1** [comment]
i have managed to delete the record in database with `$denyFriend = FriendShip::whereSenderIdAndRecipientId($recipient->id, $sender->id); `however when i use the build in "denyFriendRequest" and the user declines the request the user's is unable to resend the requests. 

Please look into this :) 
btw, thanks for a awesome package! :+1:

**Comment by hootlex** [comment]
I hadn't decide if I want to let users send friend requests again after the first is denied.
I enabled this feature in **v1.0.13**.

btw you can delete a friendship using `unfried()` method.

```php
//deletes friendship even if is denied or blocked
$recipient->unfriend($sender);
```

**Comment by Tiaan1** [comment]
Perfect :+1: thanks allot. this is great! i will be installing the new package soon :)
