### ISSUE TITLE
Any use case or samples ?

### ISSUE THREAD

**Issue by imanghafoori1** [hootlex/laravel-friendships#2]
It is dead simple to understand and sounds great.
But I can not imagine where and when it is useful...
Could you provide a sample app leveraging this nice package ?

**Comment by hootlex** [comment]
This package is useful to any project that needs users to have friends. For example in a forum app you can let your users be friends with each other  and then they can see their friends activities, or they can send messages with their friends or anything else you would like to implement in your app. 

If you want to see the package in use feel free to check the test file.
