### ISSUE TITLE
Use Eloquent::getMorphClass() intead of get_class($model)

### ISSUE THREAD

**Issue by vedmant** [hootlex/laravel-friendships#20]
Because you can set morph maps  https://laravel.com/docs/5.2/eloquent-relationships#polymorphic-relations

        Relation::morphMap([
            'users'        => \App\Models\User::class,
        ]);

**Comment by hootlex** [comment]
Could you make a pr?

**Comment by vedmant** [comment]
Sorry for late response. Yes, sure, let me do this.

**Comment by hootlex** [comment]
Sure, no problem :)
