### ISSUE TITLE
Feature request: get friends of friends

### ISSUE THREAD

**Issue by vedmant** [hootlex/laravel-friendships#21]
This would be really helpful to have, but this is quite complex task with your current DB structure, it's much easier to use two way relation for this, means for each friendship there are two records user_one => user_two and user_two => user_one, this will make complex queries much simpler.

**Comment by hootlex** [comment]
This is a very interesting feature. 
Thus, I don't like the idea of having 2 records for each friendship. Why do you think that it can't be done with the current db structure?

**Comment by vedmant** [comment]
Probably it can be done, but it's much easier with two way relationships. I can share query for that DB structure.

**Comment by hootlex** [comment]
Sure, show me what you have in mind.

The query with the current db structure will be something like this:

```php
Friendship::where('status', Status::ACCEPTED)
                  ->where(function ($query) use($friendIds){
                      $query->where(function ($q) use($friendIds){
                          $q->whereIn('sender_id', $friendIds);
                      })->orWhere(function ($q) use($friendIds){
                          $q->whereIn('recipient_id', $friendIds);
                      });
                  })->get(['sender_id', 'recipient_id']);
```

I am working on your request :)

**Comment by vedmant** [comment]
Yes, something like this, you also need to exclude your direct friends and yourself.
I made it this way, with two ways DB structure, might be not perfect:

    /**
     * Get friends of friends
     *
     * @param $user
     * @return mixed
     */
    public static function friendsOfFriends($user)
    {
        $ids = Friend::whereIn('user_id', function ($query) use ($user) {
            $query->from('friends')->select('friend_id')
                  ->where('status', 'accept')
                  ->where('user_id', $user->id);
        })->where('friend_id', '!=', $user->id)
            ->select('friend_id')->get()->pluck('friend_id');

        return self::whereIn('id', $ids)
            // Who is not friend already
            ->where(\DB::raw('0'), function ($query) use ($user) {
                $query->from('friends')->selectRaw('count(*)')
                      ->where('user_id', $user->id)
                      ->whereRaw('friend_id = users.id');
            });
    }

**Comment by hootlex** [comment]
Sure the user and his friends have to be excluded.
I have done it already, I will push in a while. 

Both ways I think you have to do 2 queries.

**Comment by hootlex** [comment]
I have added this feature in v1.0.15.
You can check my query builder [here](https://github.com/hootlex/laravel-friendships/commit/5b722996e5f1a3c60d4c92c0127206e194af9547#diff-1cda386c211a2fff2195704a0af84dbdR306).

Thanks for the suggestion.

**Comment by vedmant** [comment]
Cool, you're welcome!
