### ISSUE TITLE
acceptFriendRequest / denyFriendRequest does not work

### ISSUE THREAD

**Issue by perffy** [hootlex/laravel-friendships#24]
Hi guys,

i have successfully installed the package, but unfortunately i cannot use those functions. The send request and the block functions are working so i think the problem comes from the update() method:

public function acceptFriendRequest(Model $recipient)
    {
        return $this->findFriendship($recipient)->whereRecipient($this)->update([
            'status' => Status::ACCEPTED,
        ]);
    }

Do u have any clue why is that ?

**Comment by hootlex** [comment]
HI @perffy,
What is your issue exactly?

**Comment by perffy** [comment]
Hi @hootlex,

if i send a friend request i cannot accept/deny it. The method does not change the status in the database.

**Comment by hootlex** [comment]
What version of Laravel do you use?

**Comment by perffy** [comment]
5.2

**Comment by hootlex** [comment]
Please share your code representing this issue here.

**Comment by perffy** [comment]
This is how i accept a friend request:

public function accept_request($userToBeFriendsWith) {
		
		$user = User::findOrFail($userToBeFriendsWith);
		$this->user->acceptFriendRequest($user);

		return redirect()->back();
		
	}

**Comment by perffy** [comment]
The $user is of the User class, which is defined as: 

class User extends Authenticatable
{
	use Friendable;
        ....
}

**Comment by hootlex** [comment]
Is there a friendrequest in you database when you are trying to accept it?

**Comment by hootlex** [comment]
I've create a fresh Laravel 5.2 project and all the tests are passing..

Create a function to test the package like this:

```php
$sender = User::find(1);
$recipient = User::find(2);

$sender->befriend($recipient);
$recipient->acceptFriendRequest($sender);

dd($recipient->isFriendWith($sender));
```

The above code should return 'True'

**Comment by perffy** [comment]
hi @hootlex, 
it was late at night, so the mistake was mine. i was trying to accept my own request, thats why it was not working. I mean the sender and recipient id was the same :) 
Thanks !

**Comment by hootlex** [comment]
You are welcome :)
