### ISSUE TITLE
PostgreSQL findFriendships method issue

### ISSUE THREAD

**Issue by davidavz** [hootlex/laravel-friendships#25]
I'm using this package with PostgreSQL and this is my error when i call `findFriendships()` method

````
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: smallint ~~ unknown
LINE 1: select * from "friendships" where "status" LIKE $1 and (("se...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: select * from "friendships" where "status" LIKE 1 and (("sender_id" = 1 and "sender_type" = App\User) or ("recipient_id" = 1 and "recipient_type" = App\User)))
````

It seems that we can't use the `LIKE` operator on a smallint column type isn't it?

**Comment by hootlex** [comment]
I haven't test the package with PostgreSQL yet, I'll do it when I find some time and try to fix it.
Sorry for my late response, I was on vacation :)

**Comment by hootlex** [comment]
To achieve compatibility with PostgreSQL I've entirely removed LIKE operator from the query.
[V1.0.16](https://github.com/hootlex/laravel-friendships/releases/tag/v1.0.16) can be used with PostgreSQL. Thanks.
