### ISSUE TITLE
Friendship types

### ISSUE THREAD

**Issue by nikolaynesov** [hootlex/laravel-friendships#27]
Hi,
Is there any way to set friendship type like "Close friends/Friends/Connections". I guess it requires an extra integer pivot table column like "type"? Or is there a better approach?

**Comment by hootlex** [comment]
Hey, no it sounds like a good solution :)

**Comment by nikolaynesov** [comment]
Ok thanks. I will fork your repo then if you are not going to add this :)

**Comment by hootlex** [comment]
Sure. If you follow the current structure (class names, tests, etc) I'll be happy to accept a pr! :)
