### ISSUE TITLE
FriendshipsTest::user_can_send_a_friend_request BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::befriend()

### ISSUE THREAD

**Issue by spongi07** [hootlex/laravel-friendships#28]
When testing the application im getting de following error:

`There were 21 errors:

1) FriendshipsTest::user_can_send_a_friend_request
BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::befriend()

/public_html/laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2306
/public_html/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1388
/public_html/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:3500
/public_html/laravel/vendor/hootlex/laravel-friendships/tests/FriendshipsTest.php:17
/public_html/laravel/vendor/hootlex/laravel-friendships/tests/FriendshipsTest.php:17
`
I installed the laravel-friendships and start the test getting the error. Is there is something i did error? 
Using the new version of laravel.

**Comment by spongi07** [comment]
It fixed the problem.. but i got a last question maybe a stupid one.. I wanna attach the test project to my own project and im kind of new to laravel and composer.. Is there a wiki or how to, to get this working in my project.. I'm trying to understand both but i cant get any further..

**Comment by spongi07** [comment]
Thanks mate!

**Comment by hootlex** [comment]
no problem :)
