### ISSUE TITLE
Change friendship db table name?

### ISSUE THREAD

**Issue by IngwiePhoenix** [hootlex/laravel-friendships#3]
Hey.

I just was curios and wanted to ask, if it was possible to change the table name of the friendships without having to extend the model and creating a custom migration? Its no big deal if not, but I thought I'd bring it up anyway ^^.

Kind regards, Ingwie

**Comment by hootlex** [comment]
Hi, 
I can add a config file so you can change the database table but I don't think there are other options to configure that's why I have not done it already. 

I will check it out when I have some free time,
Thanks for your feedback.

**Comment by Advil-Robin** [comment]
You can change the names in de core files of the plugin, but I don't recomment that...

**Comment by Tiaan1** [comment]
Hi, i am still new to Laravel and found this awesome package, However a new friend request returns this on the profiles..

[{"id":2,"sender_id":3,"sender_type":"App\\User","recipient_id":1,"recipient_type":"App\\User","status":0,"created_at":"2016-03-12 18:42:10","updated_at":"2016-03-12 18:42:10"}] 

How do i get the relevant user for instance the sender id is 3 but i want to display his name how do i get that from the above ?

**Comment by nikolaynesov** [comment]
Please check this [test](https://github.com/hootlex/laravel-friendships/pull/33)

**Comment by stephane-monnot** [comment]
@hootlex as @nikolaynesov said, his [PR](https://github.com/hootlex/laravel-friendships/pull/33) allows  to change friendship db table name (See [this line](https://github.com/hootlex/laravel-friendships/commit/777c29d6493c2aff14e3ab39f09c21270f07481a#diff-b5a10b67080e340ec851603d248cd7a1R6)). So this issue should be close.
