### ISSUE TITLE
Starred friendships

### ISSUE THREAD

**Issue by masterix21** [hootlex/laravel-friendships#30]
Hi, 

have you already thought to develop the starred friendship? For example, i have a list of 100 or more friends, but only 10 of them are starred (also know like bookmark/favourite).

Thanks

**Comment by hootlex** [comment]
Hi,
I don't think it's necessary to have this feature out of the box. I don't like the idea of having a null column in all friendships (pending/blocked/aceepted/rejected).

Though, you could easily add a 'starred' field to the database and create a `starred` scope.
