### ISSUE TITLE
Method to get mutual friends

### ISSUE THREAD

**Issue by clarkewing** [hootlex/laravel-friendships#31]
Hi there, I thought it'd be nice to have a method that would give mutual friends, and maybe even another one giving the count of mutual friends. I'll try to work up some code when I get a chance.

**Comment by hootlex** [comment]
Hi @clarkewing.  It sounds great! 
I am looking forward to your pr.

**Comment by clarkewing** [comment]
I can't seem to submit my PR. First time doing this, am I missing a permission of some sort?

**Comment by hootlex** [comment]
No you don't need any extra permissions.
You have to fork the repository and then submit a pull request. To learn more about prs check github's documentation https://help.github.com/articles/using-pull-requests/

**Comment by clarkewing** [comment]
There we go, figured it out!
