### ISSUE TITLE
Recipient of a Blockade can block Sender to bypass Blockade

### ISSUE THREAD

**Issue by ShatteredMotion** [hootlex/laravel-friendships#34]
Hey,

currently, it is possible for the recipient of a blockade to block the sender and thereby replacing the old 'friendship' entry with one where recipient and sender are swapped. Then he can delete 'his' blockade.

Reason is, that in `blockFriend` the following code does not care about the kind of relationship between both models:
```php
// if there is a friendship between two users delete it
$this->findFriendship($recipient)->delete();
```

Instead, only friendships which are not of type `blocked` or those with `$this` as sender should be deleted, effectively allowing  two entries in the database for a relation between two models if both models block each other (with swapped sender and recipient).

Notice that this requires further changes in other places, as most of the current code assumes at most one database entry per pair of models. At least, `unblockFriend` must be changed as well to only delete a blockade with `$this` as sender and `$recipient` as recipient.

**Comment by hootlex** [comment]
Hey @ShatteredMotion, I solved this issue in https://github.com/hootlex/laravel-friendships/commit/ec5c3cafdd1d4abfadfa3af50ad068ab2135e3dd.
Thanks for pointing it out.

**Comment by ShatteredMotion** [comment]
Thanks 👍 

Haven't tested it yet, but it seems like the `unblockFriend` method need's a change as well to something like
```php
$this->friends()
     ->whereRecipient($recipient)
     ->where('status', Status::BLOCKED)
     ->delete();
```

Otherwise, the method may still delete both block entries as it does not care which of both models is sender and recipient of an entry at the moment.

**Comment by hootlex** [comment]
It definitely needs a change. :+1: 
I haven't finished this yet, that's why I haven't drafted a new release!
