### ISSUE TITLE
getPendingFriendships() does fetch all frindschips

### ISSUE THREAD

**Issue by mrandibilbao** [hootlex/laravel-friendships#4]
Hi,

there is a Problem with getPendingFriendships().
Everytime i use this method, it returns also accepted and blocked Friendships.

So i have to call
```
$user->getPendingFriendships()
    ->where('recipient_id', $user->id)
    ->where('status', 0);
```

Or is there an error in my code?

Thanks for this package, it's absolutely amazing

**Comment by hootlex** [comment]
Hey,

getPendingFriendships method returns all 
friend requests sent by a user and have not been yet accepted or denied. 

In which case do you need to get all the pending friendships including those where the recipient is the user?

**Comment by mrandibilbao** [comment]
Hi,

I want to show the logged in user, who has sent a request to him/her.
but this little workouround i wrote above, is working fine

**Comment by mrandibilbao** [comment]
oh sorry, i have not seen getFriendRequests yet, i'm so sorry
have a nice day

**Comment by hootlex** [comment]
No problem :)
