### ISSUE TITLE
A little help here!

### ISSUE THREAD

**Issue by darkweb2015** [hootlex/laravel-friendships#5]
I have been using this friends package with an app i am trying to build.  As a sender, I can send a friend request to a recipient, log in as a recipient and accept the request.

From the sender end, I can list the list of friends he sent the request to and build the list of friends using the getAcceptedFriendships() method, looping through the results and getting the recipient details.  However when I log in as the recipient, when I do the same, instead of the sender's name being listed, the recipient's name gets listed instead...

Any ideas as to how to fix this?

Thanks.

**Comment by hootlex** [comment]
Can you post an example of the recipient's friendships data?

**Comment by darkweb2015** [comment]
HI Alex,

Below is single data that I have in the friendships table.

id,sender_id,sender_type,recipient_id,recipient_type,status,created_at,updated_at
1,3,User,	9,User,1,2016-01-10 21:29:55,2016-01-10 21:31:18

In my code, when logged in as the sender (user id 3), I am currently looping through the array to the users friends with the code below:

```php
$friends = $user->getAcceptedFriendships();
@foreach($friends as $m)
          {{ $m->recipient->username }}<br />          
@endforeach
```

If i log in as the recipient, the above code doesnt really work too well...

**Comment by hootlex** [comment]
Hi,

try to run the tests to see if everything works as expected.

In your project root directory run this
`vendor/bin/phpunit vendor/hootlex/laravel-friendships/tests/`

**Comment by darkweb2015** [comment]
This is the error i am getting:

Fatal error: Call to undefined function createuser() in C:\xampp\htdocs\myapps\alternivelifestylers\vendor\hootlex\laravel-friendships\tests\FriedshipsTest.php on line 15

**Comment by hootlex** [comment]
Edit vendor\hootlex\laravel-friendships\tests\FriedshipsTest.php and add the above function at the bottom.

```php
function createUser($overrides = [], $amount = 1){
    return factory(\App\User::class, $amount)->create($overrides);
}
```

**Comment by hootlex** [comment]
@darkweb2015 did u solve the issue?

**Comment by darkweb2015** [comment]
Hi alex, sorry for taking  a while. Yeah I managed to resolve the isssue .  Implemented  a small code change on my end and resolved it.

**Comment by hootlex** [comment]
No problem :)
