### ISSUE TITLE
i better way to use the first() method

### ISSUE THREAD

**Issue by FWSimon** [hootlex/laravel-friendships#50]
Hi,

Thanks for a nice library.
I have a little issue when trying to "pick" some rows in my user table and doing something like this

`$recipient = User::where('firstname', 'john')->first(['firstname', 'lastname']);`

When i doing 
`Auth::user()->isFriendWith($recipient)` it will say `false` even if the 2 users is friends.
But if i remove the `first('firstname', 'lastname')` it works fine.

Is there any way to go around this "issue"? because right now I have to do this to get it to work.

```php
$recipient = User::where('firstname', 'john');
$recipient2 = User::where('firstname', 'john')->first(['firstname', 'lastname']);

Auth::user()->isFriendWith($recipient);
```

Thanks 👍

**Comment by hootlex** [comment]
Hi @FWSimon,

The problem is that you are only selecting the 'firstname' and 'lastname' attributes.
In order `isFriendWith` to make the check, it needs the Model's 'id'.

So, try to use `first()` or `first(['id', 'firstname', 'lastname'])`.

**Comment by nahid** [comment]
Here is missing `id` thats why `isFriendWith()` method does not identify the `id` attribute. So you may use `first(['id', 'firstname', 'lastname'])` instead of `first(['firstname', 'lastname'])`

**Comment by FWSimon** [comment]
@hootlex @nahid Ahh doh 👍  Thanks a lot
