### ISSUE TITLE
Non-reciprocal Friendships

### ISSUE THREAD

**Issue by skybluesofa** [hootlex/laravel-friendships#53]
I've been looking for something closer to a 'moderated follow' system rather than a 'friend' system.

The way I envision it:
- User A requests to follow a User B
- User B accepts/denies request
- If accepted, there are 2 scenarios:
  - Mutually accepted: User A now follows User B AND User B follows User A
  - Non-mutually accepted: User A now follows User B, but User B does NOT follow User A
    - Later, User B may follow User A without moderation

In essence, it's "I need to approve that you follow me, but I don't necessarily have to follow you back"

Is this something that you can see within the scope of this project, or would it be best for me to fork it? I see that [bypit asked something else similar] (https://github.com/hootlex/laravel-friendships/issues/1), do you know if that went anywhere?

I'd like to try to do this myself, but I can't seem to get the tests to pass. The error I get is:
```
Call to undefined function CreateUser()
```
I am in this directory:
```
~/Sites/laravel-application/vendor/hootlex/laravel-friendships 
```
and running this command:
```
../../bin/phpunit
```
Can you provide direction with this?

**Comment by hootlex** [comment]
Hello @skybluesofa,

Your case is kinda unusual, so I suggest to implement this feature by yourself.

In order to run the tests this way you have to autoload `hootlex/laravel-friendships/tests/helpers.php` within your `composer.json` file.

**Comment by stephane-monnot** [comment]
Can you try to add `bootstrap="./tests/helpers.php"` in phpunit.xml as below and re-run tests:
<pre><code class='xml'>&lt;phpunit backupGlobals="false"
         backupStaticAttributes="false"
         colors="true"
         <b>bootstrap="./tests/helpers.php"</b>
         convertErrorsToExceptions="true"</code></pre>

**Comment by skybluesofa** [comment]
Thank you both; I will try this tomorrow...and make sure I give credit where due if/when I get it working.
