### ISSUE TITLE
Firing events

### ISSUE THREAD

**Issue by davidavz** [hootlex/laravel-friendships#54]
Hi

Wouldn't it be nice to have by default event fired for each action?
* **friendship.sent** _When a friend request is sent_
* **friendship.accepted** _When a friend request is accepted_
* **friendship.denied** _When a friend request is denied_
* **friendship.blocked** _When a friend request is blocked_

Let me know if you are interested and I will send a PR

**Comment by hootlex** [comment]
Hi @davidavz, 
That would be awesome. Looking forward.
