### ISSUE TITLE
How to show awating friend requests

### ISSUE THREAD

**Issue by FWSimon** [hootlex/laravel-friendships#58]
Hey,

Is there anyway i can get a list of awating requests to show my user how many requests they have been sent and is not accepted?

**Comment by nikolaynesov** [comment]
Hi @FWSimon,

I think it's going to be introduced in a new version that is coming this month.
Right now you can use: $user->getPendingFriendships(); and count results. As far as I know it will give you a list of all pending requests not only what user has sent but also what another users sent to him but he did not accept yet.

To resolve it until v.2 you can introduce a Service Layer and write a custom method for awaiting friend requests. To get only incoming friendships use:

```
Friendship::whereRecipient($user);
```
Then pluck() all sender_ids from result and query for Users. Or alternatively you may use INNER JOIN. 

I am not sure it's the best way, maybe @hootlex will advise you something else.

**Comment by hootlex** [comment]
Hi,

To access the pending friend requests you can use, as @nikolaynesov said, `getPendingFriendships()`. Though, you don't have to create any new methods to find in which of them the user is the sender.

You can do it like this: `$user->getPendingFriendships()->where('sender_id', $user->id)`.
This returns an Eloquent Collection containing the friend requests that are pending and sent by the current user.

To get the count, you can simply run `$user->getPendingFriendships()->where('sender_id', $user->id)->count()`.

**Comment by FWSimon** [comment]
Thanks a lot @hootlex and @nikolaynesov :)
