### ISSUE TITLE
Reciprocal friendship

### ISSUE THREAD

**Issue by Advil-Robin** [hootlex/laravel-friendships#6]
Hi,

I have an idea/question...

So I acctually want to use this package, but I kinda need something you get 'reciprocal friendship'. So something like Facebook has:

I sent a friendshiprequest to user B.

User B accepts the friendship and now we both have each other in our friends list. Because I sent the request, I want to be a friend, and he accepts it, so we both are friends. Any idea how I can do this via your package? Or in a new release?

**Comment by hootlex** [comment]
Hello Robin,
It should work this way. I will check it out.

**Comment by hootlex** [comment]
As I can see this is the default behaviour of a Friendship.

For example:
```php
$sender = createUser();
$recipient = createUser();

$sender->befriend($recipient);
$recipient->acceptFriendRequest($sender);

//Result
$recipient->isFriendWith($sender); //true
$sender->isFriendWith($recipient); //true
```
Now `$sender->getAcceptedFriendships()` returns
```php
Illuminate\Database\Eloquent\Collection {#982
     all: [
       Hootlex\Friendships\Models\Friendship {#984
         id: 66,
         sender_id: 11,
         sender_type: "App\User",
         recipient_id: 12,
         recipient_type: "App\User",
         status: 1,
         created_at: "2016-01-15 01:46:18",
         updated_at: "2016-01-15 01:46:20",
       },
     ],
   }
```

And `$recipiend->getAcceptedFriendships()` returns the same
```php
Illuminate\Database\Eloquent\Collection {#982
     all: [
       Hootlex\Friendships\Models\Friendship {#984
         id: 66,
         sender_id: 11,
         sender_type: "App\User",
         recipient_id: 12,
         recipient_type: "App\User",
         status: 1,
         created_at: "2016-01-15 01:46:18",
         updated_at: "2016-01-15 01:46:20",
       },
     ],
   }
```

**Comment by Advil-Robin** [comment]
So, how would I be able to display everything and check if the persons are already friends?

**Comment by hootlex** [comment]
The `isFriendWith` expects a model as a parameter not an integer. In order to check if two users are friends you have to use it this way:

```php
User::find(18)->isFriendWith(User::find(4))
```

**Comment by hootlex** [comment]
I will implement a `getFriends` method which will return all User friends instead of returning Friendship objects.

**Comment by Advil-Robin** [comment]
It worked. Could you maybe also implement a function that checks if a user has a pending request of another user?

Something like 

```
User::find(Auth::id())->isPendingFriend(User::find($userdata->UID))
```

The Auth returns the current user id and the $userdata->UID is the ID of the users profile i'm watching on.
This would be handy for me like if a users has a pending request, of user X, I can display a cancel button to cancel the request.

**Comment by hootlex** [comment]
Checking friendship status between two users can be easily done via `getFriendship()`.

example:
```php
$friendship = $sender->getFriendship($recipient)
if($friendship->status == Status::PENDING){
    //your code
}
```
`$friendship` is an instance of Friendship.
```php
Hootlex\Friendships\Models\Friendship {#962
     id: 333,
     sender_id: 441,
     sender_type: "App\User",
     recipient_id: 445,
     recipient_type: "App\User",
     status: 0,
     created_at: "2016-01-16 01:36:08",
     updated_at: "2016-01-16 01:36:08",
   }
```

**Comment by Advil-Robin** [comment]
I found something else (made some new code in your package).

But when I try to count how many friends someone has, it returns 1 already on the requested friend.

So Current friends:  User A: 0 User B: 0.

When user B request a friendship to user A, User A has 1 friend (not accepted yet) and user B has 0 friends. Code that I'm using:

```
User::find($userdata->UID)->getAcceptedFriendships()->count()
```

I don't know how I can use it in any other way?

**Comment by hootlex** [comment]
Maybe you are using an old version. This is fixed in v1.0.7.

Also I have added `$user->getFriends()` in v1.0.8!

**Comment by Advil-Robin** [comment]
Cool! Now this works like a charm! Thanks for adding my requested features! If you need any help, just give me a shout :smile:

**Comment by hootlex** [comment]
Thanks! :)

**Comment by pkitatta** [comment]
Hi, can this system avoid duplicate rows of relationship. Example -  can sender_id, recipient - 3,2  be stored as 2,3, so that makes 2 records for the same relationship.

**Comment by Advil-Robin** [comment]
Well if one row already exists, then you'll have a "friendship". But if there are two rows like you say (wich you can avoid in your project) will not affect the output.
