### ISSUE TITLE
Class 'CreateFriendshipsGroupsTable' not found

### ISSUE THREAD

**Issue by mooseh** [hootlex/laravel-friendships#64]
I Installed this plugin which is amazing may i add but as i need to keep restructuring my tables as im developing when i try to migrate rollback i get the error in the title.

Confirmed error: 
Class 'CreateFriendshipsGroupsTable' not found

how can i fix this?

**Comment by hootlex** [comment]
Hello @mooseh,
Have tried running `php artisan optimize` before rolling back?

**Comment by poitras** [comment]
Well thanks you for that
