### ISSUE TITLE
getFriendRequests with recipient object

### ISSUE THREAD

**Issue by idbendriss** [hootlex/laravel-friendships#65]
Hello, 
After sending a friend request I send back a response with my friendrequest:

 public function sendFriendRequest(Request $request)
    {
           $user = Auth::user();

```
       $recipient = User::where('id', '=', $request->id)->first();


       $user->befriend($recipient);

       $friendRequests = $user->getFriendRequests();

   return  response($friendRequests, 200);
}
```

How can I get the recipient user object with that response?
 I need to display the profile image, full name ... not just sender_id. 

Thank you.

**Comment by hootlex** [comment]
Hi,
You can access these details from your model.
ex: `User::find($sender_id)->avatar`

**Comment by AlexCatch** [comment]
@hootlex How would this work with Pagination?

**Comment by BrunoMCTeixeira** [comment]
This is not good because you will have the +n1 issue on queries. Imagine you have 50 friend requests per page..
