### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by Admiraal** [hootlex/laravel-friendships#66]
Is this package out of the box compatible with Lumen?

**Comment by hootlex** [comment]
I haven't tested it with Lumen. Maybe you can try and let us know. :)

**Comment by Solomon04** [comment]
To Run on Lumen do the following
- **Step One:** `composer require hootlex/laravel-friendships`
- **Step Two:** Manually create _config/friendships.php_ with the following: 
```
<?php

return [

    'tables' => [
        'fr_pivot' => 'friendships',
        'fr_groups_pivot' => 'user_friendship_groups'
    ],

    'groups' => [
        'acquaintances' => 0,
        'close_friends' => 1,
        'family' => 2
    ]

];
```
- **Step Three:** Add `$app->configure('friendships');`  in _bootstrap/app.php_
- **Step Four:** Add `$app->register(Hootlex\Friendships\FriendshipsServiceProvider::class);`  in _bootstrap/app.php_
- **Step Five:** Run `composer require laravelista/lumen-vendor-publish` a package so you can run the vendor publish method native to laravel
- **Step Six:** Run `php artisan vendor:publish provider="Hootlex\Friendships\FriendshipsServiceProvider"` to copy the migrations to the database directory . 
**Step Seven:** Run `php artisan migrate`


Then you're all set :)

**Comment by hootlex** [comment]
@Solomon04 that's neat, thanks! Can someone confirm it's working? If so, I'd be happy to merge a PR to add it in the README.
