### ISSUE TITLE
Hi hootlex

### ISSUE THREAD

**Issue by man9035206** [hootlex/laravel-friendships#69]
How can i use this package i'm new to laravel,please help me
thank you

**Comment by gjrdiesel** [comment]
@man9035206 do you have the package installed following the instructions [here](https://github.com/hootlex/laravel-friendships#installation) and you're just looking for examples?

**Comment by HDVinnie** [comment]
I am also looking for example blades. Didn't want to start a issue over it but some example blades would be nice for a noob like me

**Comment by hootlex** [comment]
I don't see how example views will help you use the package. If you have a specific question feel free to open a new issue.
