### ISSUE TITLE
Status is ignored in Friendable::findFriendships

### ISSUE THREAD

**Issue by wuer** [hootlex/laravel-friendships#7]
Hi!
I think u have mistake in Friendable::findFriendships.
When I use method: Friendable::getPendingFriendships it should return all friendships with status=0 but it also return friendships with status=1.

    /**
     * @param $status
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    private function findFriendships($status = '%')
    {
        return Friendship::where('status', 'LIKE', $status)
            ->where(function ($q) {
                $q->whereSender($this);
            })
            ->orWhere(function ($q) {
                $q->whereRecipient($this);
            });
    }

should be:

    /**
     * @param $status
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    private function findFriendships($status = '%')
    {
        return Friendship::where('status', 'LIKE', $status)->where(function ($query) {
            $query->where(function ($q) {
                $q->whereSender($this);
            })->orWhere(function ($q) {
                $q->whereRecipient($this);
            });
        });
    }

**Comment by hootlex** [comment]
You are right. I will fix this asap. 

Thanks!

**Comment by hootlex** [comment]
This bug is fixed in v1.0.7
