### ISSUE TITLE
Find a friendship/request for a user by ID

### ISSUE THREAD

**Issue by CoderFetch** [hootlex/laravel-friendships#8]
Hey, is there any way to get a friendship or request with a given ID for a given user? (Needs to be two-way)

What I mean:
 ```php
$user->getFriendship

**Comment by CoderFetch** [comment]
```php
$user->getFriendship($id)
$other->getFriendship($same_id)
```

That's what I meant to say. Is something like this possible and could it be added?

**Comment by hootlex** [comment]
You can query any friendship by using `Friendship` model.

```php
use Hootlex\Friendships\Models\Friendship;
Friendship::find($id);
```
