### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by HDVinnie** [hootlex/laravel-friendships#82]
root@ns371466:/var/www/html# composer require hootlex/laravel-friendships
Using version ^1.0 for hootlex/laravel-friendships
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing hootlex/laravel-friendships (v1.0.21): Downloading (100%)        Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.

root@ns371466:/var/www/html# php artisan vendor:publish --provider="Hootlex\Friendships\FriendshipsServiceProvider"
Publishing complete.

root@ns371466:/var/www/html# php artisan migrate
Nothing to migrate.

Im having a issue where  php artisan vendor:publish --provider="Hootlex\Friendships\FriendshipsServiceProvider" isn't really publishing anything.

Running Laravel 5.4

**Comment by hootlex** [comment]
I just published v1.0.22. 
Could you try this one?

**Comment by HDVinnie** [comment]
Using version ^1.0 for hootlex/laravel-friendships
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating hootlex/laravel-friendships (v1.0.21 => v1.0.22): Downloading (100%)         
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.

root@ns371466:/var/www/html# php artisan vendor:publish --provider="Hootlex\Friendships\FriendshipsServiceProvider"
Publishing complete.

root@ns371466:/var/www/html# php artisan migrate
Nothing to migrate.

Still same

**Comment by hootlex** [comment]
If you run `php artisan vendor:publish` does it publish the migration files?

**Comment by hootlex** [comment]
Also, have you added `Hootlex\Friendships\FriendshipsServiceProvider::class` in your provides array within `config/app.php`?

**Comment by HDVinnie** [comment]
nope but found this in my log:

ErrorException: include(/var/www/html/vendor/hootlex/laravel-friendships/src/FriendshipsServiceProvider.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/ClassLoader.php:414

**Comment by HDVinnie** [comment]
yes   Hootlex\Friendships\FriendshipsServiceProvider::class, is in my config/app.php

**Comment by hootlex** [comment]
I tried it on a L5.4 and works fine. Could you please remove the package and follow the installation steps from the beginning?

**Comment by stephane-monnot** [comment]
Did you already have CreateFriendshipsTable or CreateFriendshipsGroupsTable class defined in your application or in another dependencies? 
In the service provider, We can find : 
```php
if (class_exists('CreateFriendshipsTable') || class_exists('CreateFriendshipsGroupsTable')) {
    return;
}
```

**Comment by HDVinnie** [comment]
I did try another package but removed the table from DB and the folder/files from /var/www/html/vendor

https://github.com/faustbrian/Laravel-Friendable/issues/11

is something conflicting as I'm still having this issue.

**Comment by hootlex** [comment]
@HDVinnie Are the migration/config files being copied when you run `vendor:publish`?

**Comment by HDVinnie** [comment]
No....others are but not this package. 

> root@ns371466:/var/www/html# php artisan vendor:publish
> Copied Directory [/vendor/rachidlaasri/laravel-installer/src/assets] To [/public/installer]
> Copied Directory [/vendor/rachidlaasri/laravel-installer/src/Views] To [/resources/views/vendor/installer]
> Copied Directory [/vendor/rachidlaasri/laravel-installer/src/Lang] To [/resources/lang]
> Copied Directory [/vendor/laravel/framework/src/Illuminate/Notifications/resources/views] To [/resources/views/vendor/notifications]
> Copied Directory [/vendor/laravel/framework/src/Illuminate/Pagination/resources/views] To [/resources/views/vendor/pagination]
> Copied Directory [/vendor/cmgmyr/messenger/src/migrations] To [/database/migrations]
> Copied Directory [/vendor/spatie/laravel-cookie-consent/resources/views] To [/resources/views/vendor/cookieConsent]
> Copied Directory [/vendor/spatie/laravel-cookie-consent/resources/lang] To [/resources/lang/vendor/cookieConsent]
> Copied Directory [/vendor/arcanedev/log-viewer/resources/views] To [/resources/views/vendor/log-viewer]
> Copied Directory [/vendor/arcanedev/log-viewer/resources/lang] To [/resources/lang/vendor/log-viewer]
> Copied Directory [/vendor/emojione/emojione/assets/png] To [/public/vendor/emojione/png]
> Copied Directory [/vendor/emojione/emojione/assets/svg] To [/public/vendor/emojione/svg]
> Copied Directory [/vendor/infinety-es/config-manager/src/resources/views] To [/resources/views/vendor/infinety/configmanager]
> Copied Directory [/vendor/infinety-es/config-manager/src/resources/lang] To [/resources/lang]
> Copied Directory [/vendor/cybercog/laravel-ban/database/migrations] To [/database/migrations]
> Copied Directory [/vendor/laravel/framework/src/Illuminate/Mail/resources/views] To [/resources/views/vendor/mail]
> Publishing complete.

Its weird as I use your other package fine and both are there.
[Imgur](http://i.imgur.com/ETJ536b.png)

**Comment by hootlex** [comment]
Did you try to reinstall it?

**Comment by HDVinnie** [comment]
yes.....well I deleted the folder for the package under the vendors. Then removed the class from app.php.

then ran composer require hootlex/laravel-friendships
added the class back to app.php
then tried to publish and migrate and same thing happened

**Comment by hootlex** [comment]
Try to copy-paste the migration and config files manually.

**Comment by HDVinnie** [comment]
still not working...when I do that and run migrate who site breaks. Must be something off with my app.

ErrorException: include(/var/www/html/database/migrations/2017_04_06_ 185824_create_friendships_table.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/ClassLoader.php:414

ErrorException: include(/var/www/html/vendor/composer/../../database/migrations/2017_04_06_ 185824_create_friendships_table.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/ClassLoader.php:414

**Comment by HDVinnie** [comment]
just a update that I reinstalled my app and package worked fine. Sorry for the hassle. App must have been borked.

**Comment by hootlex** [comment]
Glad to hear that you fixed it.
