### ISSUE TITLE
How can I get the recipient information?

### ISSUE THREAD

**Issue by BrunoMCTeixeira** [hootlex/laravel-friendships#88]
All I get is the bellow response, but I want do display the recipient information on a page without making any more queries, how can I do it?

`[
{
id: 1,
sender_id: 7,
sender_type: "App\User",
recipient_id: 15,
recipient_type: "App\User",
status: 0,
created_at: "2017-06-24 04:07:10",
updated_at: "2017-06-24 04:07:10"
}
]`

**Comment by syropian** [comment]
I think you could probably "lazy eager load" it a la

```
$user->getAllFriendships()->load('recipient');
```
