### ISSUE TITLE
[Regards]Thank you

### ISSUE THREAD

**Issue by kabelo38** [hootlex/laravel-friendships#93]
Thank you for such a nice tool and just to confirm this package works with LUMEN 5.4

Another thank you for to this API boilerplate by Hasan Hasibul  https://github.com/hasib32 I am managed to build friend relationship API system

![thank you](https://user-images.githubusercontent.com/5912376/31582620-f975de48-b188-11e7-847d-fec913db9bde.jpg)

**Comment by udanpe** [comment]
Agree. Nice job.

**Comment by hootlex** [comment]
Thanks for letting me know @kabelo38 🙂
